### ISSUE TITLE
Consider prettier default theme for 'purescript-flare'

### ISSUE THREAD

**Issue by chshersh** [sharkdp/purescript-flare#29]
I would like to use `purescript-flare` as main library for for my frontend! But it's also would be good to have some pretty theme. Something like colorful material design.. Or something simpler 🙂 I'm a CSS guru, so I can't do this... But this would be really great to have!

Here is my question about similar library on Reddit:

* https://www.reddit.com/r/purescript/comments/8nprkr/looking_for_a_library_to_create_pretty_webpages/

**Comment by sharkdp** [comment]
Thank you for the feedback!

The provided `main.css` file in the `html` folder is meant for the example cases - not as a default theme for Flare UIs. I don't think this is the right place to ask for a "pretty theme" because design is something that can (and should) be controlled independently from the frontend code and library.

Granted, Flare does attach some CSS classes to its components, but these are just meant as an additional hook for webpage designers to modify just the components that are handled by Flare. You should be able to use existing style sheets and they should work fine with Flare components.

**Comment by chshersh** [comment]
@sharkdp Thanks a lot for your answer! I understand that design better be done separately. I just wish there exist some pretty theme which I can just copy-paste. Or something like `runFlarePrettyHTML` instead of just `runFlareHTML`.

**Comment by sharkdp** [comment]
I believe that something like https://purecss.io/ or http://getskeleton.com/ should work out of the box.
